var res = {

    FONT_BOLD_X : {type:"font", name:"FONT_BOLD_X", srcs:["res/fonts/gamevina_bold.ttf","res/fonts/gamevina_bold.eot"]},
    FONT_THIN_X : {type:"font", name:"FONT_THIN_X", srcs:["res/fonts/gamevina_thin.ttf","res/fonts/gamevina_thin.eot"]},
    FONT_TITLE_X : {type:"font", name:"FONT_TITLE_X", srcs:["res/fonts/font_title.ttf","res/fonts/font_title.eot"]},

    FONT_BOLD: "res/fonts/gamevina_bold.ttf",
    FONT_THIN: "res/fonts/gamevina_thin.ttf",
    FONT_TITLE: "res/fonts/font_title.ttf",

    COMMON_SPRITE_ITEM_BACKGROUND: "res/item_background.png",
    COMMON_BTN_BLUE: "res/btn_blue.png",
    COMMON_BTN_GREEN: "res/btn_green.png",
    COMMON_BTN_YELLOW: "res/btn_yellow.png",
    COMMON_BTN_CYAN: "res/btn_cyan.png",

    INTRO_SPRITE_BG_CARD: "res/intro/bg_card.png",
    INTRO_SPRITE_BIA: "res/intro/beer_bkg.png",
    INTRO_SPRITE_BOT_BIA: "res/intro/beer_bot.png",
    INTRO_SPRITE_LUA_MACH: "res/intro/lua_mach.png",

    LOGIN_BTN_FACEBOOK: "res/btn_facebook.png",
    LOGIN_BTN_GOOGLE: "res/btn_google.png",
    LOGIN_BTN_LOGIN: "res/btn_dangnhap.png",
    LOGIN_BTN_REGISTER: "res/btn_dang_ky.png",
    LOGIN_SPRITE_EDIT_BOX: "res/edit_box.png",
    LOGIN_SPRITE_EDIT_BOX_NULL: "res/edit_box_null.png",
    LOGIN_BTN_CHOI_NGAY: "res/btn_choingay_login.png",
    LOGIN_SPRITE_GIRL: "res/sprite_cogai.png",
    LOGIN_SPRITE_LIGHT: "res/sprite_background_login.png",
    LOGIN_EDIT_PASSWORD: "res/edit_password.png",
    SHOW_GAME:{

    },

    TABLE:{

    },

    IN_GAME:{

    },

    /*
     */

    POPUP:{

    },

    POPUP_XACNHAN_BACKGROUND : "res/popup/popup_xacnhan/content_popup.png",

    POPUP_SETTING_BACKGROUND : "res/popup/popup_setting/bg_cai_dat.png",
    POPUP_SETTING_CONTENT : "res/popup/popup_setting/content_cai_dat.png",
    POPUP_SETTING_CONTENT_LINE : "res/popup/popup_setting/content_line_cai_dat.png",
    POPUP_SETTING_ON : "res/popup/popup_setting/on.png",
    POPUP_SETTING_OFF : "res/popup/popup_setting/off.png",
    POPUP_SETTING_AUTO_READY : "res/popup/popup_setting/auto_ready.png",
    POPUP_SETTING_DENY_INVITE : "res/popup/popup_setting/deny.png",
    POPUP_SETTING_MUSIC : "res/popup/popup_setting/music.png",
    POPUP_SETTING_PHONE : "res/popup/popup_setting/phone.png",
    POPUP_SETTING_SOUND : "res/popup/popup_setting/sound.png",
    POPUP_SETTING_VIBRATE : "res/popup/popup_setting/phone.png",

    item_background_png: "res/item_background.png",
    beer_bkg_png: "res/intro/beer_bkg.png",
    beer_sprite_png: "res/intro/beer_sprite.png",
    beer_bot_png: "res/intro/beer_bot.png",
    cloud_png: "res/intro/cloud.png",
    lua_mach_png: "res/intro/lua_mach.png",
    item_background: "res/item_background.png",
    sprite_background_login: "res/sprite_background_login.png",
    btn_facebook : "res/btn_facebook.png",
    btn_choingay_login : "res/btn_choingay_login.png",
    btn_dangnhap : "res/btn_dangnhap.png",
    btn_dang_ky : "res/btn_dang_ky.png",
    sprite_cogai : "res/sprite_cogai.png",
    btn_back_tlmn: "res/btn_back_tlmn.png",
    btn_moichoi: "res/popup_moichoi/btn_moichoi.png",
    btn_mokhoa: "res/btn_mokhoa.png",
    btn_khoa: "res/btn_khoa.png",
    btn_caidat: "res/btn_caidat.png",
    btn_menu: "res/btn_menu.png",
    btn_message: "res/btn_chat.png",
    btn_purcharse: "res/btn_purcharse.png",
    BGR_LISTGAMES: "res/bg_game.png",
    TABLE_BTN_PHONE: "res/btn_call.png",
    TABLE_BTN_HOPTHU: "res/btn_email.png",
    bg_songuoixem: "res/bg_songuoixem.png",
    TABLE_BK_AVATAR: "res/bk_avatar.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    TABLE_SPRITE_KEN: "res/sprite_ken.png",
    TABLE_SPRITE_NAPKEN: "res/ic_napxu.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    SPRITE_XU: "res/sprite_xu.png",
    TABLE_SPRITE_NAPXU: "res/ic_napken.png",
    SPRITE_THONGTIN: "res/sprite_thongtin.png",
    btn_tro_giup: "res/btn_tro_giup.png",
    btn_toolbar: "res/btn_toolbar.png",
    ICON_BTN_THONGBAO: "res/btn_iconthongbao.png",
    BGR_UNDERLINE: "res/unde_table.png",
    new_notify: "res/new_notify.png",
    ICON_CHAT: "res/chat.png",
    ICON_GIFTCODE: "res/btn_icongiftcode.png",
    ICON_HELP: "res/btn_iconhelp.png",
    ICON_TOP: "res/xep_hang.png",
    ICON_FRINED: "res/ban_be.png",
    ICON_PHOM_ACTIVE: "res/show_game/phom_active.png",
    ICON_WHEEL_ACTIVE: "res/show_game/wheel_active.png",
    ICON_MAU_BINH_ACTIVE: "res/show_game/mau_binh_active.png",
    ICON_TLMN_ACTIVE: "res/show_game/tlmn_active.png",
    ICON_TLMN_SOLO_ACTIVE: "res/show_game/tlmn_solo_active.png",
    ICON_BACAY_ACTIVE: "res/show_game/ba_cay_active.png",
    ICON_XOC_DIA_ACTIVE: "res/show_game/xoc_dia_active.png",
    ICON_LIENG_ACTIVE: "res/show_game/lieng_active.png",
    ICON_XITO_ACTIVE: "res/show_game/xi_to_active.png",
    ICON_TAMXINGAU_ACTIVE: "res/show_game/tamxingau_active.png",
    ICON_MINI_POKER_ACTIVE: "res/show_game/mini_poker_active.png",
    bg_popup: "res/popup_hotline/bg_popup.png",
    RS_TITLE_POPUP: "res/sprite_title_popup.png",
    IMAGE_CLOSE: "res/ic_button_close.png",
    popup_girl_hotline: "res/popup_hotline/girl_hotline.png",
    popup_btn_call: "res/popup_hotline/btn_call.png",
    LOGIN_SPRITE_BIGKEN: "res/sprite_bigken.png",
    ICON_DOI_THUONG: "res/DOI_THUONG.png",
    LOGIN_SPRITE_CARD: "res/sprite_card.png",
    LOGIN_SPRITE_GIRL: "res/sprite_cogai.png",
    ba_cay_girl: "res/ba_cay/ba_cay_girl.png",
    ba_cay_table: "res/ba_cay/ba_cay_table.png",

    // //== List Game Screen
    BTN_MENU: "res/btn_menu.png",
    // // TLMN
    BTN_MESSAGE: "res/btn_chat.png",
    BTN_PURCHASE: "res/btn_purcharse.png",
    BTN_YELLOW: "res/btn_yellow.png",
    BTN_BLUE: "res/btn_blue.png",
    BTN_CYAN: "res/btn_cyan.png",
    BTN_GREEN: "res/btn_green.png",
    sprite_table: "res/sprite_table.png",
    bg_compare_turn: "res/mau_binh/effect_lung.png",
    sprite_lung_maubinh: "res/mau_binh/sprite_lung_maubinh.png",
    btn_out_glow: "res/btn_out_glow.png",
    BGR_LISTGAMES: "res/bg_game.png",
    //table
    TABLE_BTN_BACK: "res/btn_back_tlmn.png",
    TABLE_BTN_PHONE: "res/btn_call.png",
    TABLE_BTN_CAIDAT: "res/btn_caidat.png",
    TABLE_BTN_CHOINGAY: "res/choi_ngay.png",
    TABLE_BTN_TIEN: "res/btn_tien.png",
    TABLE_BTN_HOPTHU: "res/btn_email.png",
    TABLE_INSIDE_PROGRESSBAR: "res/inside_progressbar.png",
    TABLE_SPRITE_XU: "res/sprite_xu.png",
    TABLE_SPRITE_KEN: "res/sprite_ken.png",
    TABLE_SPRITE_NAPKEN: "res/ic_napxu.png",
    TABLE_SPRITE_NAPXU: "res/ic_napken.png",
    TABLE_UNDER_PROGRESSBAR: "res/under_progressbar.png",
    TABLE_UNDER_XUKEN: "res/under_xuken.png",
    TABLE_BK_AVATAR: "res/bk_avatar.png",
    TABLE_BG_PHONGCHO: "res/bk_phongcho.png",
    TABLE_BG_PHONGFREE: "res/bk_phongfree.png",
    TABLE_BG_PHONGVIP: "res/bk_phongvip.png",
    TABLE_BTN_MENU_KEN: "res/bg_kenmenu.png",
    TABLE_BTN_MENU_XU: "res/bg_xumenu.png",
    TABLE_BTN_MENU_CUOCBAN: "res/ic_cuocban.png",
    TABLE_BTN_MENU_TAOBAN: "res/bg_menu_taoban.png",
    TABLE_BTN_MENU_REFRESH: "res/bg_menu_refresh.png",
    TABLE_BG_LST_TABLE: "res/bg_lst_table.png",
    TABLE_BG_CONTENT_CELL: "res/sprite_cell_content_table.png",
    TABLE_IC_SAO: "res/bk_iconsao.png",
    TABLE_IC_SORT: "res/ic_sort_muiten.png",
    TABLE_BTN_SORT: "res/btn_sort.png",
    bg_songuoixem: "res/bg_songuoixem.png",
    BGR_UNDERLINE: "res/unde_table.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    ICON_TITLE_ROOM_PLAY_TLMN: "res/ic_title_room_play_tlmn.png",
    ICON_TITLE_ROOM_PLAY_TLMN: "res/ic_title_room_play_tlmn.png",
    ICON_TITLE_ROOM_PLAY_PHOM: "res/ic_title_room_play_phom.png",
    ICON_TITLE_ROOM_PLAY_BACAY: "res/ic_title_room_play_bacay.png",
    ICON_TITLE_ROOM_PLAY_MAUBINH: "res/icon_title_room_mau_binh.png",
    ICON_TITLE_ROOM_PLAY_XOCDIA: "res/icon_title_room_xoc_dia.png",
    ICON_TITLE_ROOM_PLAY_TLMN_SOLO: "res/ic_title_room_play_tlmn_solo.png",
    ICON_TITLE_ROOM_PLAY_LIENG: "res/ic_title_room_play_lieng.png",
    ICON_CHOINGAY: "res/choi_ngay.png",
    XOCDIA_BTN_XINCAI:           "res/xocdia/bg_xinlamnhacai.png",
    XOCDIA_BTN_KHUNGCUOC:        "res/xocdia/khung_cuoc.png",
    XOCDIA_BTN_CUOC:             "res/xocdia/bg_cuoc.png",
    XOCDIA_DIA:                  "res/xocdia/bk_dia.png",
    XOCDIA_BAT:                  "res/xocdia/bk_bat.png",
    XOCDIA_SPRITE_DO:            "res/xocdia/sprite_le.png",
    XOCDIA_BG_4TRANG:            "res/xocdia/bg_4trang.png",
    XOCDIA_BG_3TRANG:            "res/xocdia/bg_3trang.png",
    XOCDIA_BG_1TRANG:            "res/xocdia/bg_1trang.png",
    XOCDIA_BG_0TRANG:            "res/xocdia/bg_0trang.png",
    XOCDIA_DATCHIP:              "res/xocdia/bg_chip.png",
    XOCDIA_CHIP1:                "res/xocdia/btn_chipx1.png",
    XOCDIA_CHIP5:                "res/xocdia/btn_chipx5.png",
    XOCDIA_CHIP25:               "res/xocdia/btn_chipx25.png",
    XOCDIA_CHIP50:               "res/xocdia/btn_chipx50.png",
    IC_SONGUOIXEM:               "res/xocdia/icon_nguoichoingoai.png",
    BG_SONGUOIXEM:               "res/bg_songuoixem.png",
    XOCDIA_TOTAL_CHANLE:         "res/xocdia/bg_left_total_chanle.png",
    XOCDIA_THONGKE_CHANLE:       "res/xocdia/bg_thongke_chanle.png",
    sprite_somuccuoc:            "res/ba_cay/sprite_somuccuoc.png",
    BTN_GOPGA:                   "res/ba_cay/sprite_gopga.png",
    sprite_hienthi3:             "res/ba_cay/sprite_hienthi3.png",
    nanbai_left:                 "res/ba_cay/nanbai_left.png",
    nanbai_right:                "res/ba_cay/nanbai_right.png",
    under_arrow:                 "res/vongquaymayman/under_arrow.png",
    vong_nhap_nhay:              "res/vongquaymayman/vong_nhap_nhay.png",
    vong_ngoai:                  "res/vongquaymayman/vong_ngoai.png",
    vong_trong:                  "res/vongquaymayman/vong_trong.png",
    close_pop:                   "res/common_popup/close_pop.png",
    icon_quay:                   "res/vongquaymayman/icon_quay.png",
    so_vong_quay:                "res/vongquaymayman/so_vong_quay.png",
    btn_mualuot:                 "res/vongquaymayman/btn_mualuot.png",
    hu:                          "res/vongquaymayman/hu.png",
    sprite_tienhu:               "res/vongquaymayman/sprite_tienhu.png",
    coin_left:                   "res/vongquaymayman/coin_left.png",
    arrow:                       "res/vongquaymayman/arrow.png",
    MINIPOKER_BTN_HISTORY:       "res/miniPopup/miniPoker/btn_history.png",
    btn_canquet:                 "res/vongquaymayman/btn_canquet.png",
    MINIPOKER_BACKGROUND_AVATAR: "res/miniPopup/miniPoker/background_avatar.png",
    TABLE_BG_CONTENT_CELL: "res/sprite_cell_content_table.png",
    sprite_cards_plist : "res/sprite_cards.plist"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}

var getFontName = function(resource) {
    return cc.sys.isNative ? resource.srcs[0] : resource.name;
}
