var res = {
    HelloWorld_png : "res/HelloWorld.png",
    item_background: "res/item_background.png",
    sprite_background_login: "res/sprite_background_login.png",
    btn_facebook : "res/btn_facebook.png",
    btn_choingay_login : "res/btn_choingay_login.png",
    btn_dangnhap : "res/btn_dangnhap.png",
    btn_dang_ky : "res/btn_dang_ky.png",
    edit_password : "res/edit_password.png",
    edit_login_null : "res/edit_login_null.png",
    sprite_cogai : "res/sprite_cogai.png",
    btn_back_tlmn: "res/btn_back_tlmn.png",
    btn_moichoi: "res/popup_moichoi/btn_moichoi.png",
    btn_mokhoa: "res/btn_mokhoa.png",
    btn_khoa: "res/btn_khoa.png",
    btn_caidat: "res/btn_caidat.png",
    btn_menu: "res/btn_menu.png",
    btn_message: "res/btn_chat.png",
    btn_purcharse: "res/btn_purcharse.png",
    BGR_LISTGAMES: "res/bg_game.png",
    TABLE_BTN_PHONE: "res/btn_call.png",
    TABLE_BTN_HOPTHU: "res/btn_email.png",
    bg_songuoixem: "res/bg_songuoixem.png",
    TABLE_BK_AVATAR: "res/bk_avatar.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    TABLE_SPRITE_KEN: "res/sprite_ken.png",
    TABLE_SPRITE_NAPKEN: "res/ic_napxu.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    SPRITE_XU: "res/sprite_xu.png",
    TABLE_SPRITE_NAPXU: "res/ic_napken.png",
    SPRITE_THONGTIN: "res/sprite_thongtin.png",
    btn_tro_giup: "res/btn_tro_giup.png",
    btn_toolbar: "res/btn_toolbar.png",
    ICON_BTN_THONGBAO: "res/btn_iconthongbao.png",
    BGR_UNDERLINE: "res/unde_table.png",
    new_notify: "res/new_notify.png",
    ICON_CHAT: "res/chat.png",
    ICON_GIFTCODE: "res/btn_icongiftcode.png",
    ICON_HELP: "res/btn_iconhelp.png",
    ICON_TOP: "res/xep_hang.png",
    ICON_FRINED: "res/ban_be.png",
    ICON_PHOM_ACTIVE: "res/show_game/phom_active.png",
    ICON_WHEEL_ACTIVE: "res/show_game/wheel_active.png",
    ICON_MAU_BINH_ACTIVE: "res/show_game/mau_binh_active.png",
    ICON_TLMN_ACTIVE: "res/show_game/tlmn_active.png",
    ICON_TLMN_SOLO_ACTIVE: "res/show_game/tlmn_solo_active.png",
    ICON_BACAY_ACTIVE: "res/show_game/ba_cay_active.png",
    ICON_XOC_DIA_ACTIVE: "res/show_game/xoc_dia_active.png",
    ICON_LIENG_ACTIVE: "res/show_game/lieng_active.png",
    ICON_XITO_ACTIVE: "res/show_game/xi_to_active.png",
    ICON_TAMXINGAU_ACTIVE: "res/show_game/tamxingau_active.png",
    ICON_MINI_POKER_ACTIVE: "res/show_game/mini_poker_active.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
