var res = {
    HelloWorld_png : "res/HelloWorld.png",
    item_background: "res/item_background.png",
    sprite_background_login: "res/sprite_background_login.png",
    btn_facebook : "res/btn_facebook.png",
    btn_choingay_login : "res/btn_choingay_login.png",
    btn_dangnhap : "res/btn_dangnhap.png",
    btn_dang_ky : "res/btn_dang_ky.png",
    edit_password : "res/edit_password.png",
    edit_login_null : "res/edit_login_null.png",
    sprite_cogai : "res/sprite_cogai.png",
    btn_back_tlmn: "res/btn_back_tlmn.png",
    btn_moichoi: "res/popup_moichoi/btn_moichoi.png",
    btn_mokhoa: "res/btn_mokhoa.png",
    btn_khoa: "res/btn_khoa.png",
    btn_caidat: "res/btn_caidat.png",
    btn_menu: "res/btn_menu.png",
    btn_message: "res/btn_chat.png",
    btn_purcharse: "res/btn_purcharse.png",
    BGR_LISTGAMES: "res/bg_game.png",
    TABLE_BTN_PHONE: "res/btn_call.png",
    TABLE_BTN_HOPTHU: "res/btn_email.png",
    bg_songuoixem: "res/bg_songuoixem.png",
    TABLE_BK_AVATAR: "res/bk_avatar.png",
    SPRITE_BK_XUKEN: "res/sprite_hienthixuken.png",
    TABLE_SPRITE_KEN: "res/sprite_ken.png",
    TABLE_SPRITE_NAPKEN: "res/ic_napxu.png",
    TABLE_SPRITE_NAPXU: "res/ic_napken.png",
    SPRITE_THONGTIN: "res/sprite_thongtin.png",
    btn_tro_giup: "res/btn_tro_giup.png",
    btn_doi_thuong: "res/DOI_THUONG.png",
    btn_toolbar: "res/btn_toolbar.png",
    ICON_BTN_THONGBAO: "res/btn_iconthongbao.png",
    new_notify: "res/new_notify.png",
    ICON_GIFTCODE: "res/btn_icongiftcode.png",
    ICON_HELP: "res/btn_iconhelp.png",
    ICON_TOP: "res/xep_hang.png",
    ICON_FRINED: "res/ban_be.png",
    ICON_PHOM_ACTIVE: "res/show_game/phom_active.png",
    ICON_WHEEL_ACTIVE: "res/show_game/wheel_active.png",
    ICON_MAU_BINH_ACTIVE: "res/show_game/mau_binh_active.png",
    ICON_TLMN_ACTIVE: "res/show_game/tlmn_active.png",
    ICON_TLMN_SOLO_ACTIVE: "res/show_game/tlmn_solo_active.png",
    ICON_BACAY_ACTIVE: "res/show_game/ba_cay_active.png",
    ICON_XOC_DIA_ACTIVE: "res/show_game/xoc_dia_active.png",
    ICON_LIENG_ACTIVE: "res/show_game/lieng_active.png",
    ICON_XITO_ACTIVE: "res/show_game/xi_to_active.png",
    ICON_TAMXINGAU_ACTIVE: "res/show_game/tamxingau_active.png",
    ICON_MINI_POKER_ACTIVE: "res/show_game/mini_poker_active.png",

    IMAGE_ON: "res/on.png",
    IMAGE_OFF: "res/off.png",
    IMAGE_CLOSE: "res/ic_button_close.png",
    IMAGE_SPOT: "res/null_bg.png",
    IMAGE_BG_POPUP_SETTING: "res/bg_cai_dat.png",
    IMAGE_CONTENT_POPUP_SETTING: "res/cai_dat.png",
    IMAGE_POPUP_TLMN: "res/bgr_popup_tlmn.png",
    IMAGE_MENU: "res/btn_menu.png",
    ICON_SETTING: "res/cat_dat.png",
    ICON_NAPXU: "res/nap_xu.png",
    ICON_TLMN: "res/show_game/icon_tlmn.png",
    ICON_XOC_DIA: "res/show_game/xoc_dia.png",
    ICON_BACK: "res/BACK.png",
    ICON_BACK_TLMN: "res/btn_back_tlmn.png",
    ICON_ROW_BACK: "res/arrow_back.png",
    ICON_ROW_NEXT: "res/arrow_next.png",
    ICON_PHONE: "res/btn_phone.png",
    ICON_MESSAGE_INBOX: "res/btn_hopthu.png",
    ICON_NEXT: "res/NEXT.png",
    ICON_XITO: "res/show_game/xi_to.png",
    ICON_EMAIL: "res/EMAIL.png",
    ICON_PHOM: "res/show_game/phom.png",
    ICON_TITLE_ROOM_PLAY_TLMN: "res/ic_title_room_play_tlmn.png",
    ICON_TITLE_ROOM_PLAY_TLMN_SOLO: "res/ic_title_room_play_tlmn_solo.png",
    ICON_TITLE_ROOM_PLAY_LIENG: "res/ic_title_room_play_lieng.png",
    ICON_TITLE_ROOM_PLAY_PHOM: "res/ic_title_room_play_phom.png",
    ICON_TITLE_ROOM_PLAY_BACAY: "res/ic_title_room_play_bacay.png",
    ICON_TITLE_ROOM_PLAY_MAUBINH: "res/icon_title_room_mau_binh.png",
    ICON_TITLE_ROOM_PLAY_XOCDIA: "res/icon_title_room_xoc_dia.png",
    ICON_BACAY: "res/show_game/bacay.png",
    ICON_MAUBINH: "show_game/mau_binh.png",
    ICON_TALA: "res/show_game/ta_la.png",
    ICON_SAM_2: "show_game/sam_2.png",
    ICON_DOI_THUONG: "res/DOI_THUONG.png",
    ICON_CHOINGAY: "res/choi_ngay.png",
    BGR_UNDERLINE: "res/unde_table.png",
    ICON_XU: "res/icon_xu.png",
    ICON_CHAT: "res/chat.png",
    IMAGE_POPUP_CHAT: "res/chat/bgr_popup_chat.png",
    IMAGE_SOANTINNHAN: "res/chat/sprite_soantinnhan.png",
    IMAGE_CHAT_EMOTION: "res/chat/icon_emotion.png",
    IMAGE_CHAT_EMOTION_CLICKED: "res/chat/icon_emotion_clicked.png",
    IMAGE_CHAT_TMP_CLICKED: "res/chat/icon_tmp_chat_clicked.png",
    IMAGE_CHAT_TMP: "res/chat/icon_tmp_chat.png",
    IMAGE_CONTENT_CHAT: "res/chat/bg_content.png",
    IMAGE_SEND_MESSAGE: "res/chat/btn_gui.png",
    IMAGE_MESSAGE_TEMP_2: "res/chat/sprite_text_2.png",
    IMAGE_MESSAGE_TEMP_3: "res/chat/sprite_text_3.png",
    IMAGE_MESSAGE_TEMP_4: "res/chat/sprite_text_4.png",

//doi luat
    BG_CHANGE_RULE: "res/change_rule/bg_popup.png",
    IC_CHECKBOX_CHANGERULE: "res/change_rule/bg_checkbox.png",
    BTN_CLICK_CHANGERULE: "res/change_rule/btn_clicked.png",
    IC_CHANGRULE_ARROW: "res/change_rule/icon_arrow.png",

//icon deactive
    ICON_WHEEL_DEACTIVE: "res/show_game/wheel_deactive.png",
    ICON_PHOM_DEACTIVE: "res/show_game/phom_deactive.png",
    ICON_MAUBINH_DEACTIVE: "res/show_game/mau_binh_deactive.png",
    ICON_TLMN_DEACTIVE: "res/show_game/tlmn_deactive.png",
    ICON_TLMN_SOLO_DEACTIVE: "res/show_game/tlmn_solo_deactive.png",
    ICON_BACAY_DEACTIVE: "res/show_game/ba_cay_deactive.png",
    ICON_XOC_DIA_DEACTIVE: "res/show_game/xoc_dia_deactive.png",
    ICON_LIENG_DEACTIVE: "res/show_game/lieng_deactive.png",
    ICON_XITO_DEACTIVE: "res/show_game/xi_to_deactive.png",
    ICON_TAMXINGAU_DEACTIVE: "res/show_game/tamxingau_deactive.png",
    ICON_MINI_POKER_DEACTIVE: "res/show_game/mini_poker_deactive.png",

// popup tao ban
    ICON_BTN_OK: "res/tao_ban/btn_ok.png",
    ICON_VIP: "res/tao_ban/icon_vip.png",
    POPUP_CREATE_ROOM: "res/tao_ban/popup.png",
    ICON_XU_DEACTIVE: "res/tao_ban/bgr_xu_deactive.png",
    ICON_XU_ACTIVE: "res/tao_ban/bgr_xu_active.png",
    ICON_KEN: "res/sprite_ken.png",
    SPRITE_XU: "res/sprite_xu.png",
    BGR_INPUT_NAME: "res/tao_ban/bgr_input_name.png",
    BGR_TABLE_ACTVE: "res/tao_ban/table_active.png",
    BGR_TABLE_DEACTVE: "res/tao_ban/table_deactive.png",
//pop up nap the
    LOGO_VIETTEL: "res/doi_the/logo_viettel.png",
    LOGO_MOBIFONE: "res/doi_the/logo_mobifone.png",
    LOGO_VINAPHONE: "res/doi_the/logo_vinaphone.png",
    LOGO_MEGACARD: "res/doi_the/logo_megacard.png",
    LOGO_VIETTEL_ACTIVE: "res/doi_the/logo_viettel_active.png",
    LOGO_MOBIFONE_ACTIVE: "res/doi_the/logo_mobifone_active.png",
    LOGO_VINAPHONE_ACTIVE: "res/doi_the/logo_vinaphone_active.png",
    LOGO_MEGACARD_ACTIVE: "res/doi_the/logo_megacard_active.png",
    BGR_DOITHE: "res/doi_the/bgr_khungnap.png",
    BGR_POPUP_DOITHE: "res/bkg_popup_doithe.png",
    BGR_INPUT_TEXT: "res/doi_the/input_text.png",
    BGR_CB_NHAMANG: "res/doi_the/bg_cb_nhamang.png",
    BGR_INPUT_CAPTCHA: "res/doi_the/bgr_capcha.png",
    ICON_RELOAD_CAPTCHA: "res/doi_the/icon_restart_captcha.png",
//pop up mua the
    ITEM_10K: "res/mua_the/10K.png",
    ITEM_20K: "res/mua_the/20K.png",
    ITEM_50K: "res/mua_the/50K.png",
    ITEM_100K: "res/mua_the/100K.png",
    ITEM_200K: "res/mua_the/200K.png",
    ITEM_500K :"res/mua_the/500K.png",
    BGR_BUY_CARD: "res/mua_the/bgr_buy_card.png",
    BGR_POP_UP_BUY_CARD: "res/mua_the/popup_buy_card.png",
    BGR_TITLE_BUY_CARD: "res/mua_the/title_buy_card.png",
//user info
    ICON_PENCIL: "res/user_info/btn_pencil.png",
    IMAGE_POPUP_CHANGE_PHONE: "res/user_info/popup_change_name.png",
    IMAGE_POPUP_CHANGE_PASS: "res/user_info/popup_change_pass.png",
    BGR_INPUT_PASS: "res/user_info/bgr_input_pass.png",
    BGR_INPUT_PHONE: "res/user_info/sprite_dienten.png",
    ICON_LOCK: "res/user_info/bk_iconlock.png",
    BUTTON_EXIT: "res/user_info/btn_exit.png",
    BUTTON_SAVE: "res/user_info/btn_save.png",
// friend
    BGR_FRIEND: "res/friend/bgr_friend.png",
    BGR_FRIEND_LEFT: "res/friend/bgr_friend_left.png",
    BGR_FRIEND_RI: "res/friend/circle_avatar.png",
    TAB_FRIEND_ACTIVE: "res/friend/tab_friend_active.png",
    TAB_FRIEND_UNACTIVE: "res/friend/tab_friend_unactive.png",
    TAB_ADD_FRIEND: "res/friend/bgr_add_friend.png",
    BTN_SEND_SMS: "res/friend/btn_send_sms.png",
    BTN_UNFRIEND: "res/friend/bgr_friend_right.png",
    CIRCLE_AVATAR: "res/friend/btn_unfriend.png",
    CIRCLE_AVATAR_LEFT: "res/friend/circle_avatar_left.png",
    CIRCLE_AVATAR_RIGHT: "res/friend/circle_acvatar_right.png",
    BGR_NUMBER_PLAY: "res/friend/bgr_number_play.png",
    ICON_FRIEND_XU: "res/friend/icon_xu.png",
    ICON_FRIEND_KEN: "res/friend/icon_ken.png",
    SPRITE_FRIEND: "res/friend/sprite_banbe.png",
    ICON_ADD_FRIEND: "res/friend/icon_add_friend.png",

//xoc dia
    IC_SONGUOIXEM:               "res/xocdia/icon_nguoichoingoai.png",
    XOCDIA_BTN_KHUNGCUOC:        "res/xocdia/khung_cuoc.png",
    XOCDIA_BTN_KHUNGCUOC_WIN :   "res/xocdia/khung_cuoc_win.png",
    XOCDIA_BTN_CUOC:             "res/xocdia/bg_cuoc.png",
    XOCDIA_BTN_CUOC_WIN  :       "res/xocdia/bg_cuoc_win.png",
    XOCDIA_BTN_XINCAI:           "res/xocdia/bg_xinlamnhacai.png",
    XOCDIA_BTN_HANDLER:          "res/xocdia/btn_handler.png",
    XOCDIA_BTN_GAPDOI:			"res/xocdia/btn_gapdoi.png",
    XOCDIA_CHIP1:                "res/xocdia/btn_chipx1.png",
    XOCDIA_CHIP5 :               "res/xocdia/btn_chipx5.png",
    XOCDIA_CHIP25:               "res/xocdia/btn_chipx25.png",
    XOCDIA_CHIP50:               "res/xocdia/btn_chipx50.png",
    XOCDIA_DATCHIP :             "res/xocdia/bg_chip.png",
    XOCDIA_CHIP1_ONBOARD:        "res/xocdia/chip1.png",
    XOCDIA_CHIP5_ONBOARD :       "res/xocdia/chip5.png",
    XOCDIA_CHIP25_ONBOARD:       "res/xocdia/chip25.png",
    XOCDIA_CHIP50_ONBOARD:       "res/xocdia/chip50.png",
    XOCDIA_BAT:                  "res/xocdia/bk_bat.png",
    XOCDIA_DIA:                  "res/xocdia/bk_dia.png",
    XOCDIA_NUT_DO:               "res/xocdia/nut_do.png",
    XOCDIA_NUT_TRANG:            "res/xocdia/nut_trang.png",
    XOCDIA_SPRITE_DO:            "res/xocdia/sprite_le.png",
    XOCDIA_SPRITE_TRANG :        "res/xocdia/sprite_chan.png",
    XOCDIA_CHIP1_CLICK:          "res/xocdia/btn_chipx1_clicked.png",
    XOCDIA_CHIP1_ROTATE:         "res/xocdia/chipx1_rotated.png",
    XOCDIA_CHIP5_CLICK:          "res/xocdia/btn_chipx5_clicked.png",
    XOCDIA_CHIP5_ROTATE:         "res/xocdia/chipx5_roated.png",
    XOCDIA_CHIP25_CLICK:         "res/xocdia/btn_chipx25_clicked.png",
    XOCDIA_CHIP25_ROTATE:        "res/xocdia/chipx25_rotated.png",
    XOCDIA_CHIP50_CLICK :        "res/xocdia/btn_chipx50_clicked.png",
    XOCDIA_CHIP50_ROTATE :       "res/xocdia/btn_chipx50_rotated.png",
    XOCDIA_TOTAL_CHANLE:         "res/xocdia/bg_left_total_chanle.png",
    XOCDIA_THONGKE_CHANLE:       "res/xocdia/bg_thongke_chanle.png",
    XOCDIA_BG_4TRANG:            "res/xocdia/bg_4trang.png",
    XOCDIA_BG_3TRANG:            "res/xocdia/bg_3trang.png",
    XOCDIA_BG_1TRANG:            "res/xocdia/bg_1trang.png",
    XOCDIA_BG_0TRANG:            "res/xocdia/bg_0trang.png",
    XOCDIA_NOTIFY:			   	"res/xocdia/bg_notify.png",
    XOCDIA_SELL_SMALL:           "res/xocdia/smallSell.png",
    XOCDIA_SELL_NORMAL :         "res/xocdia/sell.png",
    XOCDIA_BUY_SMALL:            "res/xocdia/smallBuy.png",
    XOCDIA_BUY_NORMAL:           "res/xocdia/buy.png",

//mail
    MAIL_CELL_BACKGROUND :       "res/mail/sprite_background.png",
    MAIL_ICON_MAIL:              "res/mail/sprite_email.png",
    MAIL_SPRITE_CONTENT:         "res/mail/sprite_noidung.png",
    MAIL_THUNG_RAC:              "res/mail/btn_thungrac.png",
    MAIL_DOC_NHAN:               "res/mail/btn_doc.png",
    MAIL_RD_ICON_MAIL:           "res/mail/sprite_da_doc_email.png",
    MAIL_RD_SPRITE_CONTENT:      "res/mail/sprite_da_doc_noidung.png",
    MAIL_RD_THUNG_RAC:           "res/mail/btn_da_doc_thungrac.png",
    MAIL_RD_DOC_NHAN:            "res/mail/btn_da_doc.png",
    MAIL_BG_DOC_MAIL:            "res/mail/sprite_docemail.png",
    MAIL_LINE_TITLE:             "res/mail/sprite_line_title.png",
    MAIL_LINE_CONTENT:           "res/mail/sprite_line_content.png",

//level up
    BG_LEVELUP:					"res/level_up/bg_level.png",

//tam xi ngau
    TXN_BG_CONTENT:				"res/tam_xi_ngau/bg_content.png",
    TXN_TXT_TAMXINGAU:			"res/tam_xi_ngau/txt_tam_xi_ngau.png",
    TXN_TAI:                     "res/tam_xi_ngau/tai.png",
    TXN_XIU:                     "res/tam_xi_ngau/xiu.png",
    TXN_BET_PLAN:                "res/tam_xi_ngau/bet_plan.png",
    TXN_DIA:                     "res/tam_xi_ngau/sprite_dia.png",
    TXN_XU:                      "res/tam_xi_ngau/xu.png",
    TXN_KEN:                     "res/tam_xi_ngau/ken.png",
    TXN_BOUND_BET:               "res/tam_xi_ngau/boundBetButton.png",
    TXN_BOUND_ADD_MONEY:         "res/tam_xi_ngau/khung_so_to.png",
    TXN_BOUND_ADD_NUMBER:        "res/tam_xi_ngau/khung_so_nho.png",
    TXN_BTN_XANH:                "res/tam_xi_ngau/btn_xanh.png",
    TXN_BTN_CHANCE:              "res/tam_xi_ngau/btn_chance.png",
    TXN_BTN_DUONG:               "res/tam_xi_ngau/btn_duong.png",
    TXN_TAI_CHIP:                "res/tam_xi_ngau/tairesult.png",
    TXN_XIU_CHIP:                "res/tam_xi_ngau/xiuresult.png",
    TXN_TAIXIU:                  "res/tam_xi_ngau/taixiu.png",
    TXN_TABLE_RESULT:            "res/tam_xi_ngau/o.png",
    TXN_ICON_USERS:              "res/tam_xi_ngau/icon_nguoichoi.png",

//mini Poker
    MINIPOKER_BG_CONTENT:        "res/miniPopup/miniPoker/popup_minipocker.png",
    MINIPOKER_BTN_BACK:          "res/miniPopup/miniPoker/btn_back.png",
    MINIPOKER_BTN_HELP:          "res/miniPopup/miniPoker/btn_help.png",
    MINIPOKER_BTN_HISTORY:       "res/miniPopup/miniPoker/btn_history.png",
    MINIPOKER_BTN_QUAY:          "res/miniPopup/miniPoker/btn_quay.png",
    MINIPOKER_BTN_CANGAT:        "res/miniPopup/miniPoker/btn_cangat.png",
    MINIPOKER_BG_CANGAT:        "res/miniPopup/miniPoker/bg_cangat.png",
    MINIPOKER_HU_BG:             "res/miniPopup/miniPoker/hu.png",
    MINIPOKER_KHUNG_LABAI:       "res/miniPopup/miniPoker/khung_hienthilabai.png",
    MINIPOKER_BGCARD_INSIDE:     "res/miniPopup/miniPoker/bg_card_inside.png",
    MINIPOKER_BGCARD_OUTSIDE:    "res/miniPopup/miniPoker/bg_card_outside.png",
    MINIPOKER_KHUNG_TEN:         "res/miniPopup/miniPoker/khung_ten.png",
    MINIPOKER_QUAY_TEXT:         "res/miniPopup/miniPoker/quay_text.png",
    MINIPOKER_CHECK_BOX:         "res/miniPopup/miniPoker/checkbox_select.png",
    MINIPOKER_CHECK_BOX_UNSELECT: "res/miniPopup/miniPoker/checkbox_unselect.png",
    MINIPOKER_CROWN:             "res/miniPopup/miniPoker/crown.png",

    MINIPOKER_ICON_UNSELECT:     "res/miniPopup/miniPoker/money_blur.png",
    MINIPOKER_ICON_1:           "res/miniPopup/miniPoker/money_1.png",
    MINIPOKER_ICON_10K_UNSELECT: "res/miniPopup/miniPoker/10k_x.png",
    MINIPOKER_ICON_2:          "res/miniPopup/miniPoker/money_2.png",
    MINIPOKER_ICON_100K_UNSELECT: "res/miniPopup/miniPoker/100k_x.png",
    MINIPOKER_ICON_3:         "res/miniPopup/miniPoker/money_3.png",
    MINIPOKER_ICON_ITEM:        "res/miniPopup/miniPoker/icon_item.png",
    MINIPOKER_ICON_X:            "res/miniPopup/miniPoker/icon_x.png",
    MINIPOKER_ICON_XU_UNSELECT:  "res/miniPopup/miniPoker/xu_x.png",
    MINIPOKER_ICON_XU:           "res/miniPopup/miniPoker/xu.png",
    MINIPOKER_ICON_KEN_UNSELECT: "res/miniPopup/miniPoker/ken_x.png",
    MINIPOKER_ICON_KEN:          "res/miniPopup/miniPoker/ken.png"

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
